### ISSUE TITLE
Programme Jumpstart

### ISSUE THREAD

**Issue by dainguieli** [ThunderCore-Developer/Jumpstart-Program#164]
Je veux voir un système de dénomination comme ENS sur ThunderCore afin que je puisse utiliser des adresses lisibles par l'homme

**Comment by Ajith0203** [comment]
Ha ha ha FuNnY🤪

**Comment by dainguieli** [comment]
Comment ça

**Comment by nguyenduc89th-rbg** [comment]
this is the best project ...I can use thundercorehub with low gas fee and I can swap easily and quickly...Thank team
