### ISSUE TITLE
Giveaway!

### ISSUE THREAD

**Issue by Nutzulik** [ThunderCore-Developer/Jumpstart-Program#174]
Follow and send your address, you will recieve 2TT in less then 48h! Let's help the community! 🤗
![3930](https://user-images.githubusercontent.com/40152628/109347939-8bb36600-787c-11eb-9732-99f286ff96d5.png)

**Comment by luki-sketch** [comment]
0x30338ebcaf62e17b3b0bf4f2d72d2bf6524f431c

**Comment by oncomwhen** [comment]
0xA748b81C0cC7918aC6B77279D23fcbd7f1571977

**Comment by MikeZy99** [comment]
0xc1179c2f12032dd972a23a14af42e9e99c69844e
