### ISSUE TITLE
ThunderCoreHub is a Great projects 👍 ,, It's very easy to use, like games, dapp browsers and the others. Glad to be joining. Hopefully Always be the best #ThunderCoreHub.

### ISSUE THREAD

**Issue by Rathomi** [ThunderCore-Developer/Jumpstart-Program#219]
ThunderCoreHub is a Great projects 👍 ,, It's very easy to use, like games, dapp browsers and the others. Glad to be joining. Hopefully Always be the best #ThunderCoreHub.

_Originally posted by @Rathomi in https://github.com/ThunderCore-Developer/Jumpstart-Program/issues/1#issuecomment-786981420_

**Comment by ajay16211621** [comment]
ThunderCoreHub is a Good Project. It's very easy to use in mobile, and laptop. I am very happy to joined in this project.  Hope this is always be the best #ThunderCoreHu
