### ISSUE TITLE
Thundercore mining

### ISSUE THREAD

**Issue by daud9** [ThunderCore-Developer/Jumpstart-Program#232]
I could see that thundercore is a great project, and the greatness about it, is the mining feature , I hope you could add stake feature also.Thanks

**Comment by CROWNT353** [comment]
Thundercore hub is a great and useful project, I will like you to add staking features and dapps to enroll in smart contract, and will be happy if you could add more crypto currency that could easily be swap. Thanks..I love thundercore

**Comment by emmax90** [comment]
0x018ca691c4875e9c323c2db527e6eee40b0deb04

Well thundercore is very legit but they need to explain to people in very simple way of doing things and mining, as in direct steps of mining instead of long process.but u have my five star
