### ISSUE TITLE
a potential project for everyone to join in the future. More missions are needed to earn T-T and grow the community

### ISSUE THREAD

**Issue by thangz27** [ThunderCore-Developer/Jumpstart-Program#257]
a potential project for everyone to join in the future. More missions are needed to earn T-T and grow the community

_Originally posted by @thangz27 in https://github.com/ThunderCore-Developer/Jumpstart-Program/issues/1#issuecomment-787030159_

**Comment by tam09cd** [comment]
a great project with great potential
