### ISSUE TITLE
Good project.. less fees..

### ISSUE THREAD

**Issue by Kingsyaitan1992** [ThunderCore-Developer/Jumpstart-Program#262]
Good project.. less fees..

_Originally posted by @Kingsyaitan1992 in https://github.com/ThunderCore-Developer/Jumpstart-Program/issues/27#issuecomment-787039725_

**Comment by Greykot78** [comment]
The project is very good. Let's have more options for staking tokens. Growth and prosperity.

**Comment by Kingsyaitan1992** [comment]
#1
