### ISSUE TITLE
Innovation 

### ISSUE THREAD

**Issue by AndrewThebe** [ThunderCore-Developer/Jumpstart-Program#265]
Please we would love to use unstoppable domains in our wallet, and also we would love a security feature were by if we want to send there us a security key that is encrypted with my phrase in order to avoid even those who might get hold of our  phrase keys from withdrawing our finances

**Comment by Greykot78** [comment]
The project is very good. Let's have more options for staking tokens. Growth and prosperity.

**Comment by AndrewThebe** [comment]
It closed today or its already closed when we engaged
