### ISSUE TITLE
Love Thundercore

### ISSUE THREAD

**Issue by 191998** [ThunderCore-Developer/Jumpstart-Program#269]
https://github.com/ThunderCore-Developer/Jumpstart-Program/issues/1#issue-798816929

**Comment by 191998** [comment]
https://github.com/ThunderCore-Developer/Jumpstart-Program/issues/1#issue-798816929

**Comment by escobar62** [comment]
![Uploading FINAL SAMPLE.jpg…]()

**Comment by MrManteka** [comment]
Estoy aprenfienfo

**Comment by MrManteka** [comment]
Alguien puede enseñar cómo funciona esto?

**Comment by escobar62** [comment]
Este enlace es para desarrolladores y thundercore es complicado de
entender, es analizar .. ¿qué ves que estás haciendo? ¿tienes edad en
criptomonedas?

MR GAILLIARD  Ludovic
