### ISSUE TITLE
https://github.com/ThunderCore-Developer/Jumpstart-Program/issues/1#issue-798816929

### ISSUE THREAD

**Issue by HE1-SIM** [ThunderCore-Developer/Jumpstart-Program#33]
https://github.com/ThunderCore-Developer/Jumpstart-Program/issues/1#issue-798816929

_Originally posted by @HE1-SIM in https://github.com/ThunderCore-Developer/Jumpstart-Program/issues/1#issuecomment-786503501_

**Comment by batuka1220** [comment]
comment

**Comment by batuka1220** [comment]
nice tt

**Comment by batuka1220** [comment]
nice nicw

**Comment by batuka1220** [comment]
Duplicate of #
