### ISSUE TITLE
ThunderCore

### ISSUE THREAD

**Issue by Haroonzarewa** [ThunderCore-Developer/Jumpstart-Program#334]
I would like to ThunderCore to have a smart contract ENRHDK

**Comment by MrNikk420** [comment]
@ThunderCore-Developer  hello. I am trying to deploy a smart contract on thundercore and pair with TT⚡ but I'm not sure on a few things. 
Am I deploying an Ethereum contract? 
I can't find any examples anywhere for a tt smart contract
