### ISSUE TITLE
Good project, I love Thundercore so much, I'll invite my friend to join this project also !

### ISSUE THREAD

**Issue by vampire3145** [ThunderCore-Developer/Jumpstart-Program#367]
Good project, I love Thundercore so much, I'll invite my friend to join this project also !

_Originally posted by @vampire3145 in https://github.com/ThunderCore-Developer/Jumpstart-Program/issues/1#issuecomment-787472653_

**Comment by vivu1** [comment]
Good project, I love Thundercore so much, I'll invite my friend to join this project also !
