### ISSUE TITLE
Thundercore-developer / jumpstart-program project airdrop

### ISSUE THREAD

**Issue by tono006** [ThunderCore-Developer/Jumpstart-Program#372]
Sangat bagus
Semoga makin banyak airdrop u token TT y

**Comment by uniquecay** [comment]
Big project in years to come

**Comment by gaw064** [comment]
Sok lah mana thunder token na siap nampung 🤭

0xd65e3c9e7d691a2e25ff39bc72c2df727d34f018

**Comment by dedeyansyah** [comment]
Good. Percepat mining dan turunkan fee wd dan swapnga

**Comment by dedeyansyah** [comment]
game_incentive&beylid-446cbce4f89d4299be1e8d01ad55470e&code-115115&gUserId-1bOYsDnt4X

**Comment by gaw064** [comment]
Ok thankyou

Pada tanggal Sel, 2 Mar 2021 12:22, ThunderCore-Developer <
notifications@github.com> menulis:
