### ISSUE TITLE
> # Claim your ThunderCore Developer Rewards

### ISSUE THREAD

**Issue by Nafeesa889** [ThunderCore-Developer/Jumpstart-Program#41]
> # Claim your ThunderCore Developer Rewards
> ThunderCore is a lightning-fast, EVM-compatible public blockchain designed to bring Blockchain to the masses. ThunderCore raised $50 million from top investors including Pantera, MetaStable, Electric Capital, Arrington XRP Capital, Hashed, Kinetic and more.
> 
> Now ThunderCore is giving away **free Thunder Tokens** to **qualifying open source developers** on GitHub.
> 
> This is an open thread for Github developers who are interested in claiming free tokens from ThunderCore Developer Rewards, which is part of the [ThunderCore Developer Jumpstart Program](https://developers.thundercore.com/docs/developer-jumpstart-program/?utm_source=github&utm_medium=developers&utm_campaign=dev_rewards).
> 
> ## I. Prerequisites
> * A GitHub account with 1 or more [open source contributions](https://docs.github.com/en/github/setting-up-and-managing-your-github-profile/why-are-my-contributions-not-showing-up-on-my-profile) in 2020.
> 
> Thunder Tokens in this program will **only** be given to open source developers on Github. You will be disqualified and your comment might be deleted if you do not meet this prerequisite.
> 
> * A [ThunderCore Hub](https://www.thundercore.com/thundercore-hub/?utm_source=github&utm_medium=developers&utm_campaign=dev_rewards) wallet address.
> 
> If you don't have ThunderCore Hub on your phone yet, you will have to [download the app](https://www.thundercore.com/thundercore-hub/?utm_source=github&utm_medium=developers&utm_campaign=dev_rewards) and use your wallet address within the mobile app.
> 
> ## II. Instructions
> ### 1. 💬 Leave a comment in this thread about a project/tool you want to see on ThunderCore, and why
> e.g. "A naming system like ENS so that I can use human-readable addresses"
> 
> This is so that we can visit your Github profile page and verify that you qualify for the free tokens. Duplicate comments will be deleted and users who do not meet the prerequisites will be disqualified.
> ![comment](https://user-images.githubusercontent.com/78369520/106553401-5880ef80-64e7-11eb-84bd-27466bcade2e.gif)
> 
> ### 2. 🔗 Copy the link to your comment
> The link should look something like `https://github.com/ThunderCore-Developer/Jumpstart-Program/issues/1#issuecomment-123456789`
> ![save](https://user-images.githubusercontent.com/78369520/106553202-e4464c00-64e6-11eb-86b9-9e309bf24cdf.gif)
> 
> ### 3. 📝 Paste the link to your comment [here](https://form.typeform.com/to/Zl2uJmzx?utm_source=github&utm_medium=developers&utm_campaign=dev_rewards) and submit.
> We respect your privacy and your personal information won't be shared with any outside organizations.
> 
> Done! 🎉We will airdrop you the free Thunder Tokens as soon as your submission has been verified!
> 
> ## III. How many tokens can I get?
> ### **Tier 1: All Developers** (500 TT)
> You don't have to be a Blockchain developer to claim your free Thunder Tokens! Follow the steps 1-3 above, [submit the form](https://form.typeform.com/to/Zl2uJmzx?utm_source=github&utm_medium=developers&utm_campaign=dev_rewards) and you will be eligible for 500 TT upon successful verification.
> 
> ### **Tier 2: DApp Developers** (5,000 TT)
> If you are someone who has developed a DApp before, great news! Please **additionally** fill in your DApp’s information(e.g. URL of the repo or app homepage) in [the form](https://form.typeform.com/to/Zl2uJmzx?utm_source=github&utm_medium=developers&utm_campaign=dev_rewards). You will be eligible for 5k TT upon successful verification.
> 
> ## IV. Want even more Thunder Tokens? Or build your startup that reaches 10k+ daily active users on day one?
> ### Tier 3: Get free Twitter marketing with TT Social (50,000 TT)
> [Deploy your DApp to ThunderCore](https://developers.thundercore.com/docs/deploy-your-own-game/?utm_source=github&utm_medium=developers&utm_campaign=dev_rewards), [submit your DApp to be listed on ThunderCore Hub](https://developers.thundercore.com/docs/guideline-submit/?utm_source=github&utm_medium=developers&utm_campaign=dev_rewards) and the news of the grand launch of your DApp will be the talk of the town in no time!
> ![quest](https://user-images.githubusercontent.com/78369520/106552788-f4a9f700-64e5-11eb-8d03-c0e646f26085.jpg)
> 
> ### Tier 4: Get 10k+ Active Crypto Users with TT Interactive Quests (Worth: ∞)
> Once your DApp has been stable on ThunderCore Hub, we can guarantee to bring at least 10k active crypto users to visit your DApp through the Interactive Quests in ThunderCore Hub.
> ![ttsocial](https://user-images.githubusercontent.com/78369520/106552796-fa074180-64e5-11eb-8712-563d610aae02.png)
> 
> Be careful about scams and phishing attempts towards GitHub users. ThunderCore will NEVER ask you for your private keys.
> 
> There is a 400,000 TT limit for this iteration of the rewards program, ThunderCore will stop distributing more rewards once successful submissions reaches the cap. Submissions will be reviewed on a **first-come-first-served basis**.
> 
> ThunderCore reserves the right to request information about, review and investigate all Program activities, and to disqualify participants if we notice any activity that we believe is abusive, fraudulent or do not meet Program requirements.

> Excellent project i like it so much

_Originally posted by @Nafeesa889 in https://github.com/ThunderCore-Developer/Jumpstart-Program/issues/1#issuecomment-786500443_

**Comment by Nafeesa889** [comment]
Excellent project i help me alot to learn about mining

**Comment by gateltelos** [comment]
amazing

**Comment by Zero9111** [comment]
Muy buen proyecto espero ganar algo y que la mina de de thundercore mine un poco más rápido
