### ISSUE TITLE
I really like this project. A very potential project

### ISSUE THREAD

**Issue by hoai27** [ThunderCore-Developer/Jumpstart-Program#420]
I really like this project. A very potential project

_Originally posted by @hoai27 in https://github.com/ThunderCore-Developer/Jumpstart-Program/issues/1#issuecomment-788156835_

**Comment by galangwb** [comment]
https://t.me/LitecoinPayLtdBot?start=ref2786673

💰 Per Referral 0.00000700 LTC Share Your referral link to your Friends & earn unlimited LTC

⚠️ Note
Fake, empty or spam users are deleted after checking.
