### ISSUE TITLE
i like ThunderCore Program and best planing project

### ISSUE THREAD

**Issue by kubilii** [ThunderCore-Developer/Jumpstart-Program#501]
i like ThunderCore Program and best planing project

_Originally posted by @kubilii in https://github.com/ThunderCore-Developer/Jumpstart-Program/issues/1#issuecomment-790034835_

**Comment by roney19** [comment]
Ótimo projeto para ThunderCore

**Comment by roney19** [comment]
Tier 1: All Developers (500 TT)
You don't have to be a Blockchain developer to claim your free Thunder Tokens! Follow the steps 1-3 above, submit the form and you will be eligible for 500 TT upon successful verification.

Tier 2: DApp Developers (5,000 TT)
If you are someone who has developed a DApp before, great news! Please additionally fill in your DApp’s information(e.g. URL of the repo or app homepage) in the form. You will be eligible for 5k TT upon successful verification.

**Comment by aditaulia08** [comment]
This is so good project . All can be easy
