### ISSUE TITLE
> I have 8 active members out of 19...but I haven't received 1000 TT tokens

### ISSUE THREAD

**Issue by hainusii** [ThunderCore-Developer/Jumpstart-Program#610]
> I have 8 active members out of 19...but I haven't received 1000 TT tokens

_Originally posted by @hainusii in https://github.com/ThunderCore-Developer/Jumpstart-Program/issues/572#issuecomment-794775070_

**Comment by myarnat** [comment]
Good luck

**Comment by nmm5055** [comment]
> > I have 8 active members out of 19...but I haven't received 1000 TT tokens
> 
> _Originally posted by @hainusii in [#572 (comment)](https://github.com/ThunderCore-Developer/Jumpstart-Program/issues/572#issuecomment-794775070)_

0xc5d509662b2eda29c7dbb52e852ab88727d78647
