### ISSUE TITLE
Thundercore developer,/ jumpstart-program

### ISSUE THREAD

**Issue by Akonuche01** [ThunderCore-Developer/Jumpstart-Program#86]
Have been waiting for this kind of opportunity to talk about it, I would like to see, a new DAPP, built on the TT blockchain that can able cross chain transaction, like the way egg DAPP, is helping us, and making the process of gaining TT more easily, but I wish an integration can be made with TRON blockchain, because its way more faster than ether and very cheaper, I would love to see a new DAPP, that can give us access to other token without going through binance, like creating a cross swapping platform to host many different tokens and coin.
0x4737d2300db39570414bc0d8c8e7d4919873a5da

**Comment by qweoi321** [comment]
Very good
